### ISSUE TITLE
Cannot clear EEPROM on Atmega32u4, and some other EEPROM Issues

### ISSUE THREAD

**Issue by 4li77l3n00b** [qmk/qmk_toolbox#290]
![屏幕截图 2021-07-26 195923](https://user-images.githubusercontent.com/31160627/126985258-225fe001-bcfe-4cd7-af3f-a89074cc82ed.png)
There is a bootloader on my atm chip (according to previous issues), since I can normally flash firmware and use the keyboard.    
My keyboard is a split one which uses EE_HANDS for handedness detection. I've tried to use the following command to manually  
flash eeprom-[left/right]hand.eep (and also reset.eep) files without validation:
`.\dfu-programmer.exe atmega32u4 flash --force --eeprom "eeprom-lefthand.eep" --suppress-validation`
It worked for handedness decision on both sides, but the RGB Matrix on the keyboard then stopped working. All RGB bulbs remained red and static(I have enabled RGB_MATRIX functions in the firmware for sure). Since the RGB Matrix system makes use of the EEPROM, I guess it was the forcible flashing operation that generated this issue.
## System Information

 - Operating system: Windows 10 Enterprise 21H1
 - QMK Toolbox version: 0.0.21

**Comment by fauxpark** [comment]
The problem in the screenshot has already been fixed in `master` and will be available in the next version - the dfu-programmer command now includes the `--suppress-validation` flag.

The issue with setting handedness resetting the RGB is normal and expected - those `.eep` files essentially set the first 14 bytes of EEPROM to 0, then the 15th byte to either 0 or 1 depending on the handedness you want to set:
![image](https://user-images.githubusercontent.com/4781841/127015891-92026327-2e50-49af-b6a5-23415c536dc4.png)
But this also means the "magic number" in the first two bytes of EEPROM is reset to `0x0000`.
![image](https://user-images.githubusercontent.com/4781841/127016564-fc9a4d7f-cc61-4182-ad18-d731dca2f539.png)

When the firmware next runs, it will see this as an invalid value, and call the function that resets everything to default, including RGB Matrix if the feature is enabled, and the default state of that is static red. All you have to do is use the RGB keycodes to change the colour and effect back to what you had before.

**Comment by 4li77l3n00b** [comment]
> The problem in the screenshot has already been fixed in `master` and will be available in the next version - the dfu-programmer command now includes the `--suppress-validation` flag.
> 
> The issue with setting handedness resetting the RGB is normal and expected - those `.eep` files essentially set the first 14 bytes of EEPROM to 0, then the 15th byte to either 0 or 1 depending on the handedness you want to set:
> ![image](https://user-images.githubusercontent.com/4781841/127015891-92026327-2e50-49af-b6a5-23415c536dc4.png)
> But this also means the "magic number" in the first two bytes of EEPROM is reset to `0x0000`.
> ![image](https://user-images.githubusercontent.com/4781841/127016564-fc9a4d7f-cc61-4182-ad18-d731dca2f539.png)
> 
> When the firmware next runs, it will see this as an invalid value, and call the function that resets everything to default, including RGB Matrix if the feature is enabled, and the default state of that is static red. All you have to do is use the RGB keycodes to change the colour and effect back to what you had before.

Thanks for that. Now it works.
