### ISSUE TITLE
QMK Toolbox Error pulling keyboard list

### ISSUE THREAD

**Issue by Grimmholtt** [qmk/qmk_toolbox#329]
I get the following error: 

Something went wrong trying to get the keyboard list from QMK.FM, you might not have a internet connection or the servers are down. 

My internet seems to be fine as I navigated to this website on the same PC. I've not seen any indication that the servers are down unless I'm looking in the wrong location.

I started the toolbox as Admin in case that was the issue, but it doesn't seem to be. 

Any Idea what I'm doing wrong?

**Comment by fauxpark** [comment]
Same issue as https://github.com/qmk/qmk_configurator/issues/1093

However, it doesn't really matter since it appears to be fixed now, and this section has already been removed for the next release anyway (https://github.com/qmk/qmk_toolbox/pull/314) as the list is not updated anymore. It does not affect the rest of the functionality of the Toolbox.
